/**
 * ikbi chat — SHELL INTEGRATION (REPL FIX 6).
 *
 * A tiny launcher so `ikbi` is available from any directory. `ikbi setup` writes an
 * executable wrapper to ~/.local/bin/ikbi (or a caller-supplied dir) that execs the CLI
 * entry against this repo, then prints what (if anything) the operator must do to put it
 * on PATH. Pure-ish: the only effects are the one file write + chmod.
 */

import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";

/** The default install directory for the launcher. */
export function defaultBinDir(): string {
  return join(homedir(), ".local", "bin");
}

/**
 * Locate the repo root (the directory holding the CLI entry) from this module's URL.
 * src/modules/chat/shell-integration.ts → up three levels is the repo root.
 */
export function repoRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  // …/src/modules/chat → …/src → … (repo root). Works for the source tree; the built
  // tree mirrors it under dist/, so resolve relative to wherever this file actually lives.
  return resolve(here, "..", "..", "..");
}

/** Build the launcher script text that execs the CLI entry against `root`. */
export function buildLauncherScript(root: string): string {
  // Prefer a built CLI when present; fall back to running the TypeScript entry via tsx.
  const distEntry = join(root, "dist", "cli", "index.js");
  const srcEntry = join(root, "src", "cli", "index.ts");
  return (
    "#!/usr/bin/env bash\n" +
    "# ikbi launcher — generated by `ikbi setup`. Runs the CLI from any directory.\n" +
    `if [ -f "${distEntry}" ]; then\n` +
    `  exec node "${distEntry}" "$@"\n` +
    "else\n" +
    `  exec node --import tsx "${srcEntry}" "$@"\n` +
    "fi\n"
  );
}

/** The result of installing (or refusing to overwrite) the launcher. */
export interface LauncherInstall {
  readonly path: string;
  readonly created: boolean;
  /** True if the install dir is already on PATH (so no further action is needed). */
  readonly onPath: boolean;
}

/**
 * Write the executable launcher to `binDir/ikbi`. Creates the directory if missing. Returns
 * the path + whether the dir is already on PATH. Throws only on an unrecoverable write error.
 */
export function installLauncher(binDir: string = defaultBinDir(), root: string = repoRoot()): LauncherInstall {
  mkdirSync(binDir, { recursive: true });
  const path = join(binDir, "ikbi");
  writeFileSync(path, buildLauncherScript(root), "utf8");
  chmodSync(path, 0o755);
  const pathEnv = process.env.PATH ?? "";
  const onPath = pathEnv.split(":").some((p) => p === binDir);
  return { path, created: true, onPath };
}

/** The human-facing message after a setup run (what to do, if anything). */
export function setupInstructions(install: LauncherInstall): string {
  const lines = [`✓ Installed ikbi launcher → ${install.path}`];
  if (install.onPath) {
    lines.push("Its directory is already on your PATH — run `ikbi repl` from anywhere.");
  } else {
    const dir = dirname(install.path);
    lines.push(`Add its directory to your PATH, then reload your shell:`);
    lines.push(`  echo 'export PATH="${dir}:$PATH"' >> ~/.bashrc && source ~/.bashrc`);
    lines.push("Then run `ikbi repl` from any directory.");
  }
  return lines.join("\n") + "\n";
}

/** Whether a launcher already exists at the default location (for `setup`'s messaging). */
export function launcherExists(binDir: string = defaultBinDir()): boolean {
  return existsSync(join(binDir, "ikbi"));
}
