/**
 * ikbi self-heal — contract.
 *
 * The self-heal loop is the last layer of "ikbi watches, reports, and repairs its OWN harness bugs":
 * a HARNESS-suspect failure (from the self-monitor classifier) becomes a candidate fix, generated by
 * running `ikbi build` on the ikbi repo itself in an ISOLATED branch, then gated hard before it is
 * ever trusted — the full ikbi test suite + the deterministic judge (correctness) and the
 * blast-radius authority gate (severity). The output is a DISPOSITION, never a merge: self-heal
 * cannot modify `main`. A verified, low-risk fix is auto-kept on its branch; anything touching a
 * guard / frozen core / broad surface waits for a human (Opus advises, the human decides); a fix
 * that fails the correctness gates is surfaced as a diagnosis, not applied. Fail-closed throughout.
 */

import type { FailureClassification } from "../self-monitor/classify.js";
import type { BlastRadius } from "../self-monitor/blast-radius.js";

export const CONTRACT_VERSION = "1.0.0";

/** The terminal disposition of one self-heal attempt — what happened to the candidate branch. */
export type SelfHealDisposition =
  /** Verified (suite + judge green) AND low blast-radius → kept on its branch for the human to merge. */
  | "applied"
  /** Verified, but touches a guard / frozen core / broad surface → held for a human decision (Opus advises). */
  | "awaiting-authorization"
  /** Could not be verified (suite or judge failed) → surfaced as a diagnosis, never applied. */
  | "diagnosed-proposal"
  /** Not acted on: the failure was not harness-suspect, or no candidate change was produced. */
  | "rejected";

/** A candidate fix produced by building on the ikbi repo in an isolated branch (from generateFix). */
export interface CandidateFix {
  /** False when the fix build produced no change at all — nothing to gate. */
  readonly produced: boolean;
  /** Repo-relative paths the candidate added or modified. */
  readonly changedFiles: readonly string[];
  /** Repo-relative paths the candidate deletes (feeds the no-test-drop anti-cheat). */
  readonly deletedFiles?: readonly string[];
  /** Total lines added + removed (a size signal for blast-radius). */
  readonly linesChanged?: number;
  /** The branch the candidate landed on (never `main`); undefined when nothing was produced. */
  readonly branch?: string;
  /** The isolated workspace id the build ran in (for the receipt trail). */
  readonly workspaceId?: string;
  /** The build's own outcome reason — carried into the diagnosis when the fix is not applied. */
  readonly buildReason?: string;
  /** True if the candidate changes a frozen contract's version/shape (raises blast-radius to MAX). */
  readonly touchesFrozenContract?: boolean;
}

/** The result of the correctness gate: the FULL ikbi test suite run against the candidate. */
export interface SuiteResult {
  /** True only when the entire suite passed. */
  readonly green: boolean;
  /** Total tests the suite ran (feeds the no-test-drop check vs testCountBefore). */
  readonly testCount?: number;
  /** A short summary of what failed, when it did — carried into the diagnosis. */
  readonly summary?: string;
}

/** The result of the deterministic judge over the candidate. */
export interface JudgeResult {
  readonly pass: boolean;
  readonly reason?: string;
}

/** The pure inputs the disposition decision is a function of — all already-computed gate results. */
export interface SelfHealGateInput {
  /** Self-heal ONLY acts on harness-suspect failures; anything else is rejected up front. */
  readonly harnessSuspect: boolean;
  /** Did the fix build produce any candidate change to gate? */
  readonly candidateProduced: boolean;
  /** Did the FULL ikbi suite pass on the candidate? */
  readonly suiteGreen: boolean;
  /** Did the deterministic judge approve the candidate? */
  readonly judgePass: boolean;
  /** The deterministic blast-radius assessment of the candidate diff. */
  readonly blastRadius: BlastRadius;
}

/** The pure verdict: the disposition plus the authority signals a caller enacts. */
export interface SelfHealVerdict {
  readonly disposition: SelfHealDisposition;
  /** True only when BOTH correctness gates (suite + judge) passed — a genuinely verified fix. */
  readonly verified: boolean;
  /** A human must decide before this candidate is ever merged. */
  readonly requiresHuman: boolean;
  /** One Opus advisory call should run before the human decides (high/max, verified fixes). */
  readonly requiresOpusReview: boolean;
  /** Plain-language justification, most-decisive first. */
  readonly reasons: readonly string[];
}

/** The impure steps the driver enacts — injected so the decision loop itself stays pure/testable. */
export interface SelfHealExecutors {
  /**
   * Generate a candidate fix: run `ikbi build` on the IKBI repo (PRO tier) in an ISOLATED branch,
   * targeting the harness-suspect failure. Resolves a CandidateFix (produced=false when it changed
   * nothing). This is the ONLY step that spends model tokens or writes to disk.
   */
  readonly generateFix: (failure: SelfHealFailure) => Promise<CandidateFix>;
  /** CORRECTNESS gate: run the full ikbi test suite (`pnpm test`) against the candidate branch. */
  readonly runSuite: (candidate: CandidateFix) => Promise<SuiteResult>;
  /** CORRECTNESS gate: the deterministic judge over the candidate. */
  readonly runJudge: (candidate: CandidateFix) => Promise<JudgeResult>;
  /** Advisory only — called when requiresOpusReview. Returns Opus's recommendation text for the human. */
  readonly opusAdvise: (ctx: OpusAdviceContext) => Promise<string>;
  /** Persist the terminal outcome as a receipt (the single audit row for this self-heal attempt). */
  readonly receipt: (result: SelfHealResult) => Promise<void>;
}

/** The harness-suspect failure that opened this self-heal attempt (from the monitor). */
export interface SelfHealFailure {
  readonly taskId: string;
  readonly classification: FailureClassification;
  readonly targetRepo: string;
  readonly reason?: string;
}

/** Everything the Opus advisory call is handed to reason about a verified-but-severe candidate. */
export interface OpusAdviceContext {
  readonly failure: SelfHealFailure;
  readonly candidate: CandidateFix;
  readonly blastRadius: BlastRadius;
}

/** The full, receipted result of one self-heal attempt. */
export interface SelfHealResult {
  readonly verdict: SelfHealVerdict;
  readonly failure: SelfHealFailure;
  /** Present once the fix build ran (absent only when short-circuited on a non-harness failure). */
  readonly candidate?: CandidateFix;
  readonly suite?: SuiteResult;
  readonly judge?: JudgeResult;
  readonly blastRadius?: BlastRadius;
  /** Opus's advice, when an advisory call ran. */
  readonly advice?: string;
  readonly reason: string;
}

/** Static driver input: the failure to heal plus the pre-fix suite baseline (for no-test-drop). */
export interface SelfHealDriverInput {
  readonly failure: SelfHealFailure;
  /** Full-suite test count BEFORE the fix — the no-test-drop anti-cheat compares against it. */
  readonly testCountBefore?: number;
}
