/**
 * ikbi `init` — guided first-run setup (GAP 2).
 *
 * Detects available provider API keys, asks 2-3 questions, and generates a working
 * .ikbi/ config. Designed for the operator who just installed ikbi — they type
 * `ikbi init`, answer a few prompts, and `ikbi` works.
 *
 * SECURITY: never prints secret values. Shows provider/key status as ✓/✗ only.
 */

import { createInterface } from "node:readline";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";


// ── Provider key detection ──────────────────────────────────────────────

interface ProviderStatus {
  name: string;
  envVar: string;
  set: boolean;
}

const KNOWN_PROVIDERS: Omit<ProviderStatus, "set">[] = [
  { name: "anthropic", envVar: "IKBI_ANTHROPIC_API_KEY" },
  { name: "openai", envVar: "IKBI_OPENAI_API_KEY" },
  { name: "deepseek", envVar: "IKBI_DEEPSEEK_API_KEY" },
  { name: "openrouter", envVar: "IKBI_OPENROUTER_API_KEY" },
  { name: "google", envVar: "IKBI_GOOGLE_API_KEY" },
  { name: "groq", envVar: "IKBI_GROQ_API_KEY" },
  { name: "xai", envVar: "IKBI_XAI_API_KEY" },
  { name: "ollama", envVar: "OLLAMA_HOST" },
];

function detectProviders(): ProviderStatus[] {
  return KNOWN_PROVIDERS.map((p) => ({
    ...p,
    set: process.env[p.envVar] !== undefined && process.env[p.envVar] !== "",
  }));
}

// ── Blessed recommendations ─────────────────────────────────────────────

interface Recommendation {
  label: string;
  desc: string;
  builder: string;
  critic: string;
  fallback?: string;
  cost: string;
}

const RECOMMENDATIONS: Record<string, Recommendation> = {
  budget: {
    label: "Budget",
    desc: "Cheapest functional setup — good for experiments and low-stakes work",
    builder: "deepseek-v4-flash",
    critic: "deepseek-v4-flash",
    cost: "~$0.05/task",
  },
  balanced: {
    label: "Balanced",
    desc: "Best quality-to-price ratio — recommended for daily use",
    builder: "claude-sonnet-4",
    critic: "deepseek-v4-pro",
    fallback: "deepseek-v4-pro",
    cost: "~$0.50/task",
  },
  quality: {
    label: "Max Quality",
    desc: "Strongest models available — for complex, multi-file refactors",
    builder: "claude-opus-4",
    critic: "claude-sonnet-4",
    cost: "~$2.00/task",
  },
  local: {
    label: "Local Only",
    desc: "No API keys needed — runs entirely on your machine via Ollama",
    builder: "ollama:qwen3",
    critic: "ollama:qwen3",
    cost: "$0 (local compute)",
  },
};

// ── Config generation ───────────────────────────────────────────────────

function generateEnvFile(rec: Recommendation, providers: ProviderStatus[]): string {
  const lines = [
    "# ikbi — generated by `ikbi init`",
    `# Profile: ${rec.label}`,
    `# Generated: ${new Date().toISOString()}`,
    "",
  ];

  for (const p of providers) {
    const icon = p.set ? "✓" : "✗";
    lines.push(`# ${icon} ${p.name}: ${p.set ? "key detected" : `set ${p.envVar} to enable`}`);
  }

  lines.push("");
  lines.push("# Builder model (primary)");
  lines.push(`IKBI_BUILDER_MODEL=${rec.builder}`);
  lines.push("");
  lines.push("# Critic model (verification)");
  lines.push(`IKBI_CRITIC_MODEL=${rec.critic}`);
  if (rec.fallback) {
    lines.push("");
    lines.push("# Fallback model (when primary fails)");
    lines.push(`IKBI_FALLBACK_MODEL=${rec.fallback}`);
  }
  lines.push("");

  return lines.join("\n");
}

function ensureDotIkbi(projectDir: string): string {
  const dir = join(projectDir, ".ikbi");
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  return dir;
}

// ── Interactive flow ─────────────────────────────────────────────────────

async function prompt(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer: string) => resolve(answer.trim()));
  });
}

export async function runInit(): Promise<void> {
  const out = (s: string): boolean => process.stdout.write(s);

  out("\nikbi init — guided first-run setup\n");
  out("──────────────────────────────────\n\n");

  // Step 1: detect providers
  const providers = detectProviders();
  const found = providers.filter((p) => p.set);

  out("Detected providers:\n");
  for (const p of providers) {
    const icon = p.set ? "✓" : "✗";
    out(`  ${icon} ${p.name.padEnd(14)} ${p.envVar}\n`);
  }
  out("\n");

  if (found.length === 0) {
    out("No API keys detected! You'll need at least one provider configured.\n");
    out("Set an API key (e.g., export IKBI_ANTHROPIC_API_KEY=xxx) and re-run `ikbi init`,\n");
    out("or choose the 'Local Only' profile if you have Ollama running.\n\n");
  }

  // Step 2: choose profile
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  out("Available profiles:\n");
  let idx = 1;
  const keys = Object.keys(RECOMMENDATIONS);
  for (const k of keys) {
    const r = RECOMMENDATIONS[k]!;
    out(`  [${idx}] ${r.label.padEnd(12)} ${r.desc} (${r.cost})\n`);
    idx++;
  }
  out("\n");

  const choice = await prompt(rl, `Choose a profile [1-${keys.length}, default: 2]: `);
  const chosenIdx = choice === "" ? 1 : Math.max(0, Math.min(keys.length - 1, parseInt(choice, 10) - 1));
  const rec = RECOMMENDATIONS[keys[chosenIdx]!]!;

  out(`\nSelected: ${rec.label}\n`);
  out(`  Builder:  ${rec.builder}\n`);
  out(`  Critic:   ${rec.critic}\n`);
  if (rec.fallback) out(`  Fallback: ${rec.fallback}\n`);
  out(`  Est cost: ${rec.cost}\n\n`);

  // Step 3: confirm
  const confirm = await prompt(rl, "Write config to .ikbi/ and .env? [Y/n]: ");
  if (confirm.toLowerCase() === "n" || confirm.toLowerCase() === "no") {
    out("Aborted. Run `ikbi init` again when ready.\n\n");
    rl.close();
    return;
  }

  // Step 4: write config
  const projectDir = process.cwd();
  const dotIkbi = ensureDotIkbi(projectDir);
  const envContent = generateEnvFile(rec, providers);
  const envPath = join(projectDir, ".env");
  const backupPath = join(projectDir, ".env.bak");

  // Back up existing .env if present
  if (existsSync(envPath)) {
    writeFileSync(backupPath, readFileSync(envPath));
    out(`Backed up existing .env → .env.bak\n`);
  }

  // Write .env (merge with existing)
  const existing = existsSync(envPath) ? readFileSync(envPath, "utf-8") : "";
  const sep = existing.length > 0 && !existing.endsWith("\n") ? "\n" : "";
  const header = existing ? `${sep}\n# === ikbi init additions below ===\n` : "";
  writeFileSync(envPath, existing + header + envContent);

  out(`\n✓ Config written to ${envPath}\n`);
  out(`✓ .ikbi/ directory created at ${dotIkbi}\n\n`);

  // Step 5: post-setup
  out("──────────────────────────────────\n");
  out("ikbi is ready!\n\n");
  out("  ikbi              Start an interactive coding session\n");
  out("  ikbi \"fix auth\"   Start a session with a prompt\n");
  out("  ikbi build \"...\"  Headless build/repair (CI/scripts)\n");
  out("  ikbi doctor       Check configuration health\n\n");

  rl.close();
}
